version: '3'

services:
  db:
    build: ./docker/db
    # TODO
    # environment:
    #   - POSTGRES_DB=postgres
    #   - POSTGRES_PASSWORD=odoo
    #   - POSTGRES_USER=odoo
    #   - PGDATA=/var/lib/postgresql/data/pgdata
    # volumes:
    #   # docker-compose restart db (reload config too)
    #   - ./services/db/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
  odoo:
    build:
      context: ./
      dockerfile: ./docker/odoo/Dockerfile
    command: ./root/deploy-odoo/deploy/runit
    stdin_open: true
    tty: true
    volumes:
      - ./deploy:/root/deploy-odoo/deploy
      - ./envs:/root/deploy-odoo/envs
      - ./deploy/runit:/roo/deploy-odoo/deploy/runit
      - ./odoo:/opt/odoo
    depends_on:
      - db
    ports:
      # Keep port mapping equal to ensure `report.url` works.
      # Change with docker-compose.override.yml (see example).
      - 8069:8069
